// Seed data shaped exactly like the Base44 entities under implementation/base44/entities.
// Every lead here exists to make one guard in communicationEngine.js reachable from
// the UI: the 48-hour floor, channel rotation, template reuse, Section 12 suppression,
// the Cold-lead content block, and the four hard stops.

import { hoursBefore } from "@/lib/utils";
import { buildExtras } from "@/store/seedExtra";

let counter = 0;
const id = (prefix) => `${prefix}_${String(++counter).padStart(3, "0")}`;

export function buildSeed(now = new Date()) {
  counter = 0;

  const templates = [
    {
      id: "tpl_ack_wa",
      name: "Acknowledgement — enquiry received",
      purpose: "Confirm the enquiry reached us and ask for a suitable call time",
      channel: "WhatsApp",
      nurture_step: 1,
      nurture_label: "Acknowledgement",
      disease: "Any",
      temperature: "Any",
      body: "Hello {{name}}, this is {{hospital}}. We received your enquiry about {{disease}}. When would be a good time for our team to call you?",
      media_type: "None",
      approval_status: "Approved",
      approved_by: "Meera Raghavan",
      approved_at: hoursBefore(720, now),
      version: 2,
    },
    {
      id: "tpl_edu_rcs",
      name: "Education — condition explainer",
      purpose: "Explain the condition, its symptoms and the risk of delaying consultation",
      channel: "RCS",
      nurture_step: 2,
      nurture_label: "Education",
      disease: "Any",
      temperature: "Any",
      body: "Understanding {{disease}}: what causes it, the symptoms to watch, and why early consultation matters.",
      media_type: "Patient Education Poster",
      approval_status: "Approved",
      approved_by: "Meera Raghavan",
      approved_at: hoursBefore(700, now),
      version: 1,
    },
    {
      id: "tpl_trust_rcs",
      name: "Trust — doctor profile card",
      purpose: "Build confidence in the treating doctor with credentials and case volume",
      channel: "RCS",
      nurture_step: 3,
      nurture_label: "Trust",
      disease: "Any",
      temperature: "Any",
      body: "Dr. {{doctor}} — {{years}} years, {{cases}}+ procedures performed at {{hospital}}.",
      media_type: "Doctor Image",
      approval_status: "Approved",
      approved_by: "Meera Raghavan",
      approved_at: hoursBefore(690, now),
      version: 3,
    },
    {
      id: "tpl_treat_wa",
      name: "Treatment Understanding — procedure walkthrough",
      purpose: "Set expectations on procedure duration, recovery and hospital stay",
      channel: "WhatsApp",
      nurture_step: 4,
      nurture_label: "Treatment Understanding",
      disease: "Any",
      temperature: "Any",
      body: "The procedure takes about {{duration}}. Most patients are discharged the same day and back to routine work within {{recovery}}.",
      media_type: "Procedure Benefit Card",
      approval_status: "Approved",
      approved_by: "Meera Raghavan",
      approved_at: hoursBefore(500, now),
      version: 1,
    },
    {
      id: "tpl_proof_rcs",
      name: "Social Proof — patient testimonial",
      purpose: "Show a comparable patient outcome to reduce procedure anxiety",
      channel: "RCS",
      nurture_step: 5,
      nurture_label: "Social Proof",
      disease: "Any",
      temperature: "Any",
      body: "\"I was back at work in four days.\" — {{patient}}, treated at {{hospital}}.",
      media_type: "Testimonial Image",
      approval_status: "Approved",
      approved_by: "Meera Raghavan",
      approved_at: hoursBefore(480, now),
      version: 1,
    },
    {
      id: "tpl_fin_wa",
      name: "Financial Support — insurance and EMI",
      purpose: "Explain insurance cover, EMI options and how to reach financial counseling",
      channel: "WhatsApp",
      nurture_step: 6,
      nurture_label: "Financial Support",
      disease: "Any",
      temperature: "Any",
      body: "Your treatment may be covered by insurance. EMI options start at {{emi}} per month. Our counselor can walk you through both.",
      media_type: "Financial Counseling Information",
      approval_status: "Approved",
      approved_by: "Meera Raghavan",
      approved_at: hoursBefore(460, now),
      version: 1,
    },
    {
      id: "tpl_action_rcs",
      name: "Action — book your consultation",
      purpose: "Convert intent into a booked appointment slot",
      channel: "RCS",
      nurture_step: 7,
      nurture_label: "Action",
      disease: "Any",
      temperature: "Any",
      body: "Pick a slot that suits you at {{branch}}. Video consultation is also available.",
      media_type: "Appointment Reminder Creative",
      approval_status: "Approved",
      approved_by: "Meera Raghavan",
      approved_at: hoursBefore(440, now),
      version: 1,
    },
    {
      id: "tpl_price_offer",
      name: "Limited-period package price",
      purpose: "Communicate the current package price to a price-sensitive patient",
      channel: "WhatsApp",
      nurture_step: 6,
      nurture_label: "Financial Support",
      disease: "Any",
      temperature: "Hot",
      body: "Package price this month: {{price}}. Valid until {{date}}.",
      media_type: "None",
      is_price_offer: true,
      approval_status: "Approved",
      approved_by: "Meera Raghavan",
      approved_at: hoursBefore(300, now),
      version: 1,
    },
    {
      id: "tpl_surgery_push",
      name: "Surgery recommended — act now",
      purpose: "Push a clinically advised surgery towards a booking decision",
      channel: "WhatsApp",
      nurture_step: 7,
      nurture_label: "Action",
      disease: "Any",
      temperature: "Hot",
      body: "Your condition needs surgery soon. Shall we block a date this week?",
      media_type: "None",
      is_surgery_push: true,
      approval_status: "Approved",
      approved_by: "Meera Raghavan",
      approved_at: hoursBefore(290, now),
      version: 1,
    },
    {
      id: "tpl_pending_review",
      name: "Camp announcement — free screening",
      purpose: "Invite long-cycle patients to a free screening camp near them",
      channel: "RCS",
      nurture_step: 2,
      nurture_label: "Education",
      disease: "Any",
      temperature: "Cold",
      body: "Free screening camp at {{branch}} on {{date}}. Walk in, no appointment needed.",
      media_type: "Location Card",
      approval_status: "Pending Approval",
      version: 1,
    },
    {
      id: "tpl_draft_interest",
      name: "Interest check-in",
      purpose: "Check whether the patient is still interested",
      channel: "WhatsApp",
      nurture_step: 1,
      nurture_label: "Acknowledgement",
      disease: "Any",
      temperature: "Any",
      body: "Hi {{name}}, are you interested in proceeding with the treatment?",
      media_type: "None",
      approval_status: "Draft",
      version: 1,
    },
  ];

  const leads = [
    {
      id: "lead_001",
      patient_name: "Priya Sharma",
      phone_number: "+91 98450 11223",
      lead_type: "Inbound",
      disease: "Cataract",
      source: "Meta Ads",
      campaign: "Cataract — Jayanagar — Aug",
      lead_status: "Follow-up Plan Activated",
      stage: 9,
      agent_name: "Nikhil Rao",
      branch: "Jayanagar",
      rcs_supported: true,
      number_valid: true,
      created_at: hoursBefore(72, now),
      plan: { temperature: "Hot", day: 3, activated_at: hoursBefore(72, now) },
    },
    {
      id: "lead_002",
      patient_name: "Ramesh Kumar",
      phone_number: "+91 98860 44551",
      lead_type: "Inbound",
      disease: "Knee Replacement",
      source: "Google Ads",
      campaign: "Ortho — Whitefield — Aug",
      lead_status: "Follow-up Plan Activated",
      stage: 9,
      agent_name: "Nikhil Rao",
      branch: "Whitefield",
      rcs_supported: true,
      number_valid: true,
      created_at: hoursBefore(36, now),
      plan: { temperature: "Hot", day: 2, activated_at: hoursBefore(36, now) },
    },
    {
      id: "lead_003",
      patient_name: "Anita Desai",
      phone_number: "+91 99000 77332",
      lead_type: "Inbound",
      disease: "Varicose Veins",
      source: "Website",
      campaign: "Organic — Website",
      lead_status: "Follow-up Plan Activated",
      stage: 9,
      agent_name: "Sneha Pillai",
      branch: "Jayanagar",
      rcs_supported: false,
      number_valid: true,
      created_at: hoursBefore(200, now),
      plan: { temperature: "Cold", day: 8, activated_at: hoursBefore(200, now) },
    },
    {
      id: "lead_004",
      patient_name: "Suresh Reddy",
      phone_number: "+91 90080 23145",
      lead_type: "Inbound",
      disease: "Hernia",
      source: "Meta Ads",
      campaign: "General Surgery — Aug",
      lead_status: "Appointment Booked",
      stage: 11,
      agent_name: "Sneha Pillai",
      branch: "Whitefield",
      rcs_supported: true,
      number_valid: true,
      created_at: hoursBefore(120, now),
      plan: { temperature: "Warm", day: 5, appointment_booked: true, activated_at: hoursBefore(120, now) },
    },
    {
      id: "lead_005",
      patient_name: "Mohan Rao",
      phone_number: "+91 98801 65422",
      lead_type: "Outbound",
      disease: "Piles",
      source: "Camp",
      campaign: "Camp — Kanakapura Road",
      lead_status: "Follow-up Plan Activated",
      stage: 9,
      agent_name: "Nikhil Rao",
      branch: "Jayanagar",
      opted_out: true,
      rcs_supported: true,
      number_valid: true,
      created_at: hoursBefore(300, now),
      plan: { temperature: "Warm", day: 7, opted_out: true, activated_at: hoursBefore(300, now) },
    },
    {
      id: "lead_006",
      patient_name: "Fatima Sheikh",
      phone_number: "+91 97400 88190",
      lead_type: "Inbound",
      disease: "Gallstones",
      source: "Meta Ads",
      campaign: "General Surgery — Aug",
      lead_status: "First Contact Attempted",
      stage: 4,
      agent_name: "Sneha Pillai",
      branch: "Whitefield",
      rcs_supported: true,
      number_valid: true,
      created_at: hoursBefore(20, now),
      plan: { temperature: "Not Connected", day: 1, activated_at: hoursBefore(20, now) },
    },
    {
      id: "lead_007",
      patient_name: "Vikram Nair",
      phone_number: "+91 96320 51170",
      lead_type: "IPD",
      disease: "Cataract",
      source: "Referral",
      campaign: "Doctor referral",
      lead_status: "Converted",
      stage: 20,
      agent_name: "Nikhil Rao",
      branch: "Jayanagar",
      rcs_supported: true,
      number_valid: true,
      created_at: hoursBefore(400, now),
      plan: { temperature: "Hot", day: 7, patient_converted: true, activated_at: hoursBefore(400, now) },
    },
    {
      id: "lead_008",
      patient_name: "Lakshmi Iyer",
      phone_number: "+91 91480 30076",
      lead_type: "Inbound",
      disease: "Thyroid",
      source: "Google Ads",
      campaign: "Endocrine — Aug",
      lead_status: "Follow-up Plan Activated",
      stage: 9,
      agent_name: "Sneha Pillai",
      branch: "Jayanagar",
      rcs_supported: true,
      number_valid: true,
      created_at: hoursBefore(260, now),
      plan: { temperature: "Warm", day: 9, activated_at: hoursBefore(260, now) },
    },
    {
      id: "lead_009",
      patient_name: "Gopal Menon",
      phone_number: "+91 90000 00000",
      lead_type: "Inbound",
      disease: "Cataract",
      source: "Meta Ads",
      campaign: "Cataract — Jayanagar — Aug",
      lead_status: "First Contact Attempted",
      stage: 4,
      agent_name: "Nikhil Rao",
      branch: "Jayanagar",
      number_valid: false,
      rcs_supported: false,
      created_at: hoursBefore(48, now),
      plan: { temperature: "Not Connected", day: 3, activated_at: hoursBefore(48, now) },
    },
  ];

  const comm = (lead, overrides) => ({
    id: id("comm"),
    lead_id: lead.id,
    lead_type: lead.lead_type,
    patient_name: lead.patient_name,
    phone_number: lead.phone_number,
    agent_name: lead.agent_name,
    branch: lead.branch,
    suppressed: false,
    link_clicked: false,
    delivery_status: "Delivered",
    ...overrides,
  });

  const byId = Object.fromEntries(leads.map((l) => [l.id, l]));

  const communications = [
    // lead_001 — last message 60h ago on WhatsApp: clear to send, rotation says RCS.
    comm(byId.lead_001, {
      channel: "WhatsApp",
      template_id: "tpl_ack_wa",
      template_name: "Acknowledgement — enquiry received",
      nurture_step: 1,
      protocol_day: 1,
      body_snapshot: "Hello Priya, this is Sunrise Hospital. We received your enquiry about Cataract...",
      sent_at: hoursBefore(60, now),
      delivered_at: hoursBefore(60, now),
      read_at: hoursBefore(59, now),
      delivery_status: "Read",
    }),

    // lead_002 — last message 12h ago: TOO_SOON until the 48-hour floor clears.
    comm(byId.lead_002, {
      channel: "WhatsApp",
      template_id: "tpl_ack_wa",
      template_name: "Acknowledgement — enquiry received",
      nurture_step: 1,
      protocol_day: 1,
      body_snapshot: "Hello Ramesh, this is Sunrise Hospital. We received your enquiry about Knee Replacement...",
      sent_at: hoursBefore(12, now),
      delivered_at: hoursBefore(12, now),
      delivery_status: "Delivered",
    }),

    // lead_003 — Cold lead, two touches done, RCS unsupported so the fallback is MMS.
    comm(byId.lead_003, {
      channel: "WhatsApp",
      template_id: "tpl_ack_wa",
      template_name: "Acknowledgement — enquiry received",
      nurture_step: 1,
      protocol_day: 1,
      body_snapshot: "Hello Anita, this is Sunrise Hospital...",
      sent_at: hoursBefore(196, now),
      delivered_at: hoursBefore(196, now),
      read_at: hoursBefore(190, now),
      delivery_status: "Read",
    }),
    comm(byId.lead_003, {
      channel: "MMS",
      template_id: "tpl_edu_rcs",
      template_name: "Education — condition explainer",
      nurture_step: 2,
      protocol_day: 8,
      body_snapshot: "Understanding Varicose Veins: what causes it...",
      sent_at: hoursBefore(100, now),
      delivered_at: hoursBefore(100, now),
      delivery_status: "Delivered",
    }),

    // lead_004 — appointment booked mid-plan; the next scheduled send was suppressed, not dropped.
    comm(byId.lead_004, {
      channel: "WhatsApp",
      template_id: "tpl_ack_wa",
      template_name: "Acknowledgement — enquiry received",
      nurture_step: 1,
      protocol_day: 1,
      body_snapshot: "Hello Suresh, this is Sunrise Hospital...",
      sent_at: hoursBefore(118, now),
      delivered_at: hoursBefore(118, now),
      read_at: hoursBefore(117, now),
      replied_at: hoursBefore(116, now),
      delivery_status: "Replied",
    }),
    comm(byId.lead_004, {
      channel: "RCS",
      template_id: "tpl_trust_rcs",
      template_name: "Trust — doctor profile card",
      nurture_step: 3,
      protocol_day: 3,
      scheduled_at: hoursBefore(70, now),
      suppressed: true,
      suppression_reason: "Appointment has been booked",
      delivery_status: "Suppressed",
    }),

    // lead_005 — opted out after two touches.
    comm(byId.lead_005, {
      channel: "WhatsApp",
      template_id: "tpl_ack_wa",
      template_name: "Acknowledgement — enquiry received",
      nurture_step: 1,
      protocol_day: 1,
      body_snapshot: "Hello Mohan, this is Sunrise Hospital...",
      sent_at: hoursBefore(296, now),
      delivered_at: hoursBefore(296, now),
      delivery_status: "Delivered",
    }),
    comm(byId.lead_005, {
      channel: "RCS",
      template_id: "tpl_edu_rcs",
      template_name: "Education — condition explainer",
      nurture_step: 2,
      protocol_day: 3,
      sent_at: hoursBefore(240, now),
      delivered_at: hoursBefore(240, now),
      read_at: hoursBefore(239, now),
      delivery_status: "Read",
    }),
    comm(byId.lead_005, {
      channel: "WhatsApp",
      template_id: "tpl_treat_wa",
      template_name: "Treatment Understanding — procedure walkthrough",
      nurture_step: 4,
      protocol_day: 5,
      scheduled_at: hoursBefore(180, now),
      suppressed: true,
      suppression_reason: "Patient has opted out",
      delivery_status: "Suppressed",
    }),

    // lead_007 — converted; the failed send is why the CONVERTED hard stop exists.
    comm(byId.lead_007, {
      channel: "WhatsApp",
      template_id: "tpl_ack_wa",
      template_name: "Acknowledgement — enquiry received",
      nurture_step: 1,
      protocol_day: 1,
      body_snapshot: "Hello Vikram, this is Sunrise Hospital...",
      sent_at: hoursBefore(396, now),
      delivered_at: hoursBefore(396, now),
      read_at: hoursBefore(395, now),
      replied_at: hoursBefore(394, now),
      link_clicked: true,
      delivery_status: "Replied",
    }),
    comm(byId.lead_007, {
      channel: "RCS",
      template_id: "tpl_action_rcs",
      template_name: "Action — book your consultation",
      nurture_step: 7,
      protocol_day: 3,
      sent_at: hoursBefore(340, now),
      delivered_at: hoursBefore(340, now),
      read_at: hoursBefore(339, now),
      replied_at: hoursBefore(338, now),
      link_clicked: true,
      delivery_status: "Replied",
    }),

    // lead_008 — a full compliant sequence, plus one failed send for the M9 numbers.
    comm(byId.lead_008, {
      channel: "WhatsApp",
      template_id: "tpl_ack_wa",
      template_name: "Acknowledgement — enquiry received",
      nurture_step: 1,
      protocol_day: 1,
      sent_at: hoursBefore(256, now),
      delivered_at: hoursBefore(256, now),
      read_at: hoursBefore(255, now),
      delivery_status: "Read",
    }),
    comm(byId.lead_008, {
      channel: "RCS",
      template_id: "tpl_edu_rcs",
      template_name: "Education — condition explainer",
      nurture_step: 2,
      protocol_day: 3,
      sent_at: hoursBefore(208, now),
      delivered_at: hoursBefore(208, now),
      read_at: hoursBefore(207, now),
      link_clicked: true,
      delivery_status: "Read",
    }),
    comm(byId.lead_008, {
      channel: "WhatsApp",
      template_id: "tpl_treat_wa",
      template_name: "Treatment Understanding — procedure walkthrough",
      nurture_step: 4,
      protocol_day: 5,
      sent_at: hoursBefore(160, now),
      delivered_at: hoursBefore(160, now),
      read_at: hoursBefore(159, now),
      replied_at: hoursBefore(158, now),
      delivery_status: "Replied",
    }),
    comm(byId.lead_008, {
      channel: "RCS",
      template_id: "tpl_proof_rcs",
      template_name: "Social Proof — patient testimonial",
      nurture_step: 5,
      protocol_day: 7,
      sent_at: hoursBefore(96, now),
      delivery_status: "Failed",
      failure_reason: "Handset does not support RCS and MMS fallback was unavailable",
    }),
    comm(byId.lead_008, {
      channel: "WhatsApp",
      template_id: "tpl_fin_wa",
      template_name: "Financial Support — insurance and EMI",
      nurture_step: 6,
      protocol_day: 9,
      sent_at: hoursBefore(50, now),
      delivered_at: hoursBefore(50, now),
      read_at: hoursBefore(49, now),
      delivery_status: "Read",
    }),
  ];

  const interactions = [
    {
      id: id("call"),
      lead_id: "lead_001",
      lead_type: "Inbound",
      agent_name: "Nikhil Rao",
      interaction_date: hoursBefore(62, now),
      contact_outcome: "Connected",
      patient_response: "Interested",
      patient_said: "Wants the surgery done but needs to arrange money first, asked about EMI options.",
      agent_explained: "Explained the laser procedure, day-care discharge and that insurance may cover it.",
      objection_category: "Financial",
      objection_raised: "EMI required",
      material_shared: "Acknowledgement — enquiry received",
      next_action: "Financial Counseling",
      next_action_at: hoursBefore(-6, now),
      feedback: "Patient is keen, blocked only on money. Counselor callback promised.",
    },
    {
      id: id("call"),
      lead_id: "lead_006",
      lead_type: "Inbound",
      agent_name: "Sneha Pillai",
      interaction_date: hoursBefore(18, now),
      contact_outcome: "Not Connected",
      not_connected_reason: "No answer",
      attempt_number: 2,
      double_dial_complete: true,
      feedback: "Double dial complete on day 1. Alternative-time slot not yet tried.",
    },
  ];

  const audit = [
    {
      id: id("audit"),
      at: hoursBefore(70, now),
      actor: "Meera Raghavan",
      action: "TEMPLATE_APPROVED",
      entity: "Template",
      entity_id: "tpl_trust_rcs",
      detail: "Version 3 approved — doctor credentials updated",
    },
    {
      id: id("audit"),
      at: hoursBefore(70, now),
      actor: "System",
      action: "MESSAGE_SUPPRESSED",
      entity: "Communication",
      entity_id: "lead_004",
      detail: "Appointment has been booked — scheduled RCS send suppressed, not dropped",
    },
  ];

  // The nine leads above are the guard fixtures and are asserted on by name in the tests. The rest
  // of the working desk lives in seedExtra.js — thirty-six leads that put every Today bucket,
  // every §17 appointment state and seven §23 closure categories in front of whoever opens this.
  const extras = buildExtras(now);

  return {
    leads: [...leads, ...extras.leads],
    templates,
    communications: [...communications, ...extras.communications],
    interactions: [...interactions, ...extras.interactions],
    audit,
  };
}
